# Generated by Django 5.1.15 on 2026-07-31 08:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composer', '0019_merge_20260630_1149'),
        ('social_accounts', '0012_add_devto_platform'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_automation_audit_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandBrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tone', models.CharField(blank=True, default='', max_length=500)),
                ('persona', models.TextField(blank=True, default='')),
                ('products', models.JSONField(blank=True, default=list)),
                ('audiences', models.JSONField(blank=True, default=list)),
                ('guidelines', models.TextField(blank=True, default='')),
                ('forbidden_topics', models.JSONField(blank=True, default=list)),
                ('knowledge_base', models.TextField(blank=True, default='')),
                ('default_language', models.CharField(default='id', max_length=20)),
                ('monthly_token_limit', models.PositiveIntegerField(default=1000000)),
                ('monthly_cost_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_brain', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_brand_brain',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('brief', models.TextField()),
                ('objective', models.CharField(blank=True, default='', max_length=500)),
                ('target_audience', models.CharField(blank=True, default='', max_length=500)),
                ('platforms', models.JSONField(default=list)),
                ('cadence_per_week', models.PositiveSmallIntegerField(default=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('materialized', 'Added to content calendar'), ('failed', 'Failed')], db_index=True, default='draft', max_length=24)),
                ('strategy', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.PositiveIntegerField(default=0)),
                ('generation_error', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_campaigns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_campaigns', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_campaigns', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=40)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField()),
                ('caption_variants', models.JSONField(blank=True, default=list)),
                ('visual_prompt', models.TextField(blank=True, default='')),
                ('video_script', models.TextField(blank=True, default='')),
                ('content_pillar', models.CharField(blank=True, default='', max_length=120)),
                ('call_to_action', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('materialized', 'Added to composer')], db_index=True, default='pending_approval', max_length=24)),
                ('moderation_status', models.CharField(choices=[('passed', 'Passed'), ('flagged', 'Flagged')], db_index=True, default='passed', max_length=16)),
                ('moderation_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='ai_automation.campaign')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_source_draft', to='composer.post')),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_content_drafts', to='social_accounts.socialaccount')),
            ],
            options={
                'db_table': 'ai_automation_content_draft',
                'ordering': ['scheduled_for', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=12)),
                ('prompt', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('waiting_provider', 'Waiting for provider'), ('ready_for_review', 'Ready for review'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('external_job_id', models.CharField(blank=True, default='', max_length=255)),
                ('output_url', models.URLField(blank=True, default='', max_length=2000)),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_jobs', to='ai_automation.contentdraft')),
            ],
            options={
                'db_table': 'ai_automation_media_generation_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=80)),
                ('provider', models.CharField(max_length=60)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=16)),
                ('moderation_status', models.CharField(blank=True, default='', max_length=20)),
                ('input_digest', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_events', to='workspaces.workspace')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='ai_automation.campaign')),
            ],
            options={
                'db_table': 'ai_automation_usage_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='idx_ai_usage_workspace_date')],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('purpose', models.TextField(blank=True, default='')),
                ('template', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_prompt_versions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_prompt_template',
                'ordering': ['key', '-version'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'key', 'version'), name='uniq_ai_prompt_workspace_key_version')],
            },
        ),
    ]
