# Generated by Django 5.1.15 on 2026-08-01 05:05

import apps.common.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_automation', '0002_traffic_strategy_fields'),
        ('organizations', '0002_organization_billing_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_provider_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_audit_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_automation_provider_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('openai_compatible', 'OpenAI-compatible')], max_length=32)),
                ('api_key', apps.common.encryption.EncryptedTextField()),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(max_length=200)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('test_result', models.CharField(choices=[('untested', 'Untested'), ('success', 'Connected'), ('failure', 'Connection failed')], default='untested', max_length=16)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_provider_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_connections', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_automation_provider_connection',
                'ordering': ['priority', 'provider'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'priority'], name='idx_ai_provider_org_active')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_ai_provider_per_organization')],
            },
        ),
    ]
